stages:
  - parser
  - ansible
  
first_job:
    stage: parser
    script:
      - echo "Detected useful changes, starting ..."      
    tags:
      - shell
    rules:
    - changes:
        - "dev/vmdefs.xlsx"
      
parse_job_1:
    before_script:
      - cd dev
      - https_proxy=172.22.108.7:80 pip3 install -r requirements.txt 
    stage: parser 
    script:
      - python3 convert_to_csv.py
    tags:
      - shell
    rules:
    - changes:
        - "dev/vmdefs.xlsx"

parse_job_2:
    stage: parser
    before_script:
      - cd dev
    script:
      - python3 convert_to_yml.py
    tags:
      - shell
    needs:
      - parse_job_1
    rules:
    - changes:
        - "dev/vmdefs.xlsx"
      