stages:
  - trigger_on_excel
  - convert_to_csv
  - convert_to_yaml

first_job:
    stage: trigger_on_excel
    script:
      - git diff --name-only HEAD^ HEAD -- '*.xlsx' | grep -q 'vmdefs.xlsx' && echo "Ajout ou modif du fichier de def. VM." || exit 0
      # Pipeline steps
      - echo "Starting ..."      
    rules:
    - changes:
        - "vmdefs.xlsx"

parse_job_1:
    before_script:
      - pip3 install pandas 
    stage: convert_to_csv 
    script:
      #- echo $CI_PROJECT_DIR
      - python3 /opt/infrastructure-linux/terraform/dev/convert_to_csv.py

parse_job_2:
    stage: convert_to_yaml
    script:
      - python3 convert_to_yaml.py