stages:
  - parse_trigger #dummy stage to trigger the pipeline
  - parse_convert_to_csv 
  - parse_convert_to_yml 
  - ansible
  - tf_check
  
first_job:
    stage: parse_trigger 
    script:
      - echo "Detected useful changes, starting ..."      
    tags:
      - shell
    rules:
    - changes:
        - "dev/vmdefs.xlsx" #if change happens here, the pipeline is triggered 
      
parse_job_1:
    before_script:
      - cd dev
      - https_proxy=172.22.108.7:80 pip3 install -r requirements.txt 
    stage: parse_convert_to_csv 
    script:
      - python3 convert_to_csv.py
    tags:
      - shell
    
parse_job_2:
    stage: parse_convert_to_yml
    before_script:
      - cd dev
    script:
      - python3 convert_to_yml.py
    tags:
      - shell
    needs:
      - parse_job_1
      
ansible_playbook_generation:
    stage: ansible 
    script:
      - cd dev 
      - ansible-playbook main.yml 

terraform_check:
    stage: tf_check
    script:
      - cd dev
      - terraform validate
      - terraform plan --var-file /opt/infrastructure-linux/terraform/dev/.infra.tfvars 