lan_vms:  
  VSL-DEV-APT-001:  
    name: "VSL-DEV-APT-001"  
    descr: "VSL-DEV-APT-001"  
    hostname: "vsl-dev-apt-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 20480  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.138"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
