lan_vms:  
  RH-TESTSERVER-JH:  
    name: "RH-TESTSERVER-JH"  
    descr: "TEST"  
    hostname: "rh-testserver-jh"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["VLAN-128-Server"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 2048  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "20"  
    ip: "192.168.128.98"  
    net_prefix: "24"  
    gw: "192.168.128.1"  
    satellite_env: DEV_TEST
  
