lan_vms:  
  VSL-DEV-IIS-001:  
    name: "VSL-DEV-IIS-001"  
    descr: "VSL-DEV-IIS-001"  
    hostname: "vsl-dev-iis-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["VLAN-20-Legacy-Server"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_RH_PGSQL"]  
    mem: 16384  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.17.20.148"  
    net_prefix: "24"  
    gw: "172.17.20.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-IDB-001:  
    name: "VSL-DEV-IDB-001"  
    descr: "VSL-DEV-IDB-001"  
    hostname: "vsl-dev-idb-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["VLAN-20-Legacy-Server"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_RH_PGSQL"]  
    mem: 8192  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.17.20.149"  
    net_prefix: "24"  
    gw: "172.17.20.1"  
    satellite_env: DEV_TEST
  
