dmz_vms:  
  VSL-PPR-RPE-001:  
    name: "VSL-PPR-RPE-001"  
    hostname: "vsl-ppr-rpe-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-02  
    network: PPR_REVERSE_PROXY_EXT  
    datastore: NUT_DMZ_EXT_DC2_01  
    folder:   
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.74.1"  
    net_prefix: "24"  
    gw: "172.24.74.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.74.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: RECETTE
  
