lan_vms:  
  LU718:  
    name: "LU718"  
    descr: "VM TEST"  
    hostname: "lu718"  
    datacenter: nutanix.dc1  
    image: rhel8-dc1  
    cluster: pe_lu650  
    subnet: var.ahv_650_network["Production"]  
    storage: var.ahv_650_storage["NUT_AHV_DC1_01"]  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "200.1.1.105"  
    net_prefix: "24"  
    gw: "200.1.1.240"  
    satellite_env: DEV_TEST
  
