lan_vms:  
  VSL-POC-DTH-001:  
    name: "VSL-POC-DTH-001"  
    descr: "DATATHINGS POC"  
    hostname: "vsl-poc-dth-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: cluster651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 32768  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "500"  
    ip: "192.168.25.119"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
  VSL-TST-AXW-002:  
    name: "VSL-TST-AXW-002"  
    descr: "AXWAY LAN TEST"  
    hostname: "vsl-tst-axw-002"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: cluster651  
    subnet: var.ahv_651_network["VLAN_42"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "192.168.42.158"  
    net_prefix: "24"  
    gw: "192.168.42.1"  
    satellite_env: DEV_TEST
  
  VSL-PRO-AXW-002:  
    name: "VSL-PRO-AXW-002"  
    descr: "AXWAY LAN PROD"  
    hostname: "vsl-pro-axw-002"  
    datacenter: nutanix.dc1  
    image: rhel8-dc1  
    cluster: cluster650  
    subnet: var.ahv_650_network["VLAN_42"]  
    storage: var.ahv_650_storage["NUT_AHV_DC1_01"]  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "192.168.42.157"  
    net_prefix: "24"  
    gw: "192.168.42.1"  
    satellite_env: DEV_TEST
  
dmz_vms:  
  VSL-PRO-AXW-001:  
    name: "VSL-PRO-AXW-001"  
    hostname: "vsl-pro-axw-001"  
    datacenter: NUT-DMZ-DC01  
    content_library_item: esx_lib1_item  
    host: nut-dmz-01  
    network: PRO_AXWAY  
    datastore: NUT_DMZ_INT_DC1_to_DC2  
    folder: /DMZ  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.23.83.1"  
    net_prefix: "24"  
    gw: "172.23.83.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.23.83.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-TST-AXW-001:  
    name: "VSL-TST-AXW-001"  
    hostname: "vsl-tst-axw-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-02  
    network: TST_AXWAY  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.26.83.1"  
    net_prefix: "24"  
    gw: "172.26.83.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.26.83.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
