lan_vms:  
  LU717:  
    name: "LU717"  
    descr: "VM TEST"  
    hostname: "lu717"  
    datacenter: nutanix.dc3  
    image: esx_lib2_item  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["Production"]  
    storage: var.ahv_651_storage["NUT_AHV_DC1_01"]  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "200.1.1.106"  
    net_prefix: "24"  
    gw: "200.1.1.240"  
    satellite_env: DEV_TEST
  
