dmz_vms:  
  VSL-PRO-SRO-001 :  
    name: "VSL-PRO-SRO-001 "  
    hostname: "vsl-pro-sro-001"  
    datacenter: NUT-DMZ-DC01  
    content_library_item: esx_lib1_item  
    host: nut-dmz-05  
    network: PRO_SAP_ROUTER_EXT  
    datastore: NUT_DMZ_EXT_DC1_to_DC2  
    folder: /DMZ  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "20"  
    ip: "172.23.76.1"  
    net_prefix: "24"  
    gw: "172.23.76.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.23.76.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
