dmz_vms:  
  VSL-PRO-ATQ-001_BKP3.1_D_PRO:  
    name: "VSL-PRO-ATQ-001_BKP3.1_D_PRO"  
    hostname: "vsl-pro-atq-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-04  
    network: DMZ_PRO_APPMOBIL  
    datastore: NUT_DMZ_INT_DC2_to_DC1  
    folder: /DMZ/Tinqin/Servers  
    mem: 24576  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.22.148.8 "  
    net_prefix: "24"  
    gw: "172.22.148.1 "  
    vm_ip_last_octet: 8   
    gw_ip_last_octet: 1   
    subnet: 172.22.148.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
