dmz_vms:  
  VSL-PRO-SQU-001:  
    name: "VSL-PRO-SQU-001"  
    hostname: "vsl-pro-squ-001"  
    datacenter: NUT-DMZ-DC01  
    content_library_item: esx_lib1_item  
    host: nut-dmz-07  
    network: DMZ_PRO_BITB_GW  
    datastore: NUT_DMZ_EXT_DC1_to_DC2  
    folder:   
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.22.108.50"  
    net_prefix: "24"  
    gw: "172.22.108.1"  
    vm_ip_last_octet: 50  
    gw_ip_last_octet: 1  
    subnet: 172.22.108.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
