lan_vms:  
  VSL-POC-DTH-001:  
    name: "VSL-POC-DTH-001"  
    descr: "DATATHINGS POC"  
    hostname: "vsl-poc-dth-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: cluster651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 32768  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "500"  
    ip: "192.168.25.119"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
