dmz_vms:  
  VSL-TST-AXW-003:  
    name: "VSL-TST-AXW-003"  
    hostname: "vsl-tst-axw-003"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-04  
    network: TST_AXWAY  
    datastore: NUT_DMZ_INT_DC2_01  
    folder:   
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.26.83.2"  
    net_prefix: "24"  
    gw: "172.26.83.254"  
    vm_ip_last_octet: 2  
    gw_ip_last_octet: 254  
    subnet: 172.26.83.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
