lan_vms:  
  VSL-DEV-RPI-001:  
    name: "VSL-DEV-RPI-001"  
    descr: "VSL-DEV-RPI-001"  
    hostname: "vsl-dev-rpi-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["VLAN_42"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "192.168.42.174"  
    net_prefix: "24"  
    gw: "192.168.42.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-ATQ-001:  
    name: "VSL-DEV-ATQ-001"  
    descr: "VSL-DEV-ATQ-001"  
    hostname: "vsl-dev-atq-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["VLAN_42"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 4096  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "192.168.42.175"  
    net_prefix: "24"  
    gw: "192.168.42.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-ALT-001:  
    name: "VSL-DEV-ALT-001"  
    descr: "VSL-DEV-ALT-001"  
    hostname: "vsl-dev-alt-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["VLAN_42"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "192.168.42.176"  
    net_prefix: "24"  
    gw: "192.168.42.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-ALN-001:  
    name: "VSL-DEV-ALN-001"  
    descr: "VSL-DEV-ALN-001"  
    hostname: "vsl-dev-aln-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["VLAN_42"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 8192  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "192.168.42.177"  
    net_prefix: "24"  
    gw: "192.168.42.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-EPT-001:  
    name: "VSL-DEV-EPT-001"  
    descr: "VSL-DEV-EPT-001"  
    hostname: "vsl-dev-ept-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["VLAN_42"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 4096  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "192.168.42.178"  
    net_prefix: "24"  
    gw: "192.168.42.1"  
    satellite_env: DEV_TEST
  
