dmz_vms:  
  LU686:  
    name: "LU686"  
    hostname: "lu686"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-04  
    network: DMZ_PRO_INT_RHEL_MGMT  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.22.160.2"  
    net_prefix: "24"  
    gw: "172.22.160.1"  
    vm_ip_last_octet: 2  
    gw_ip_last_octet: 1  
    subnet: 172.22.160.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
