lan_vms:  
  VSL-TEST:  
    name: "VSL-TEST"  
    descr: "VSL-TEST"  
    hostname: "vsltest"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["521-REC_ESIGN_INT"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.25.21.2"  
    net_prefix: "24"  
    gw: "172.25.21.254"  
    satellite_env: DEV_TEST
  
