lan_vms:  
  VSL-PRO-AIA-001:  
    name: "VSL-PRO-AIA-001"  
    descr: "VSL-PRO-AIA-001"  
    hostname: "vsl-pro-aia-001"  
    datacenter: nutanix.dc1  
    image: rhel8-dc1  
    cluster: pe_lu650  
    subnet: var.ahv_650_network["PRO_AIA_324"]  
    storage: var.ahv_650_storage["NUT_AHV_DC1_01"]  
    mem: 24576  
    cpu: 8  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.23.24.1 "  
    net_prefix: "24"  
    gw: "172.23.24.253 "  
    satellite_env: DEV_TEST
  
  VSL-REC-AIA-001:  
    name: "VSL-REC-AIA-001"  
    descr: "VSL-REC-AIA-001"  
    hostname: "vsl-rec-aia-001"  
    datacenter: nutanix.dc1  
    image: rhel8-dc1  
    cluster: pe_lu650  
    subnet: var.ahv_650_network["REC_AIA_524"]  
    storage: var.ahv_650_storage["NUT_AHV_DC1_01"]  
    mem: 24576  
    cpu: 8  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.25.24.1"  
    net_prefix: "24"  
    gw: "172.25.24.253 "  
    satellite_env: DEV_TEST
  
  VSL-REC-IAI-001:  
    name: "VSL-REC-IAI-001"  
    descr: "VSL-REC-IAI-001"  
    hostname: "vsl-rec-iai-001"  
    datacenter: nutanix.dc1  
    image: rhel8-dc1  
    cluster: pe_lu650  
    subnet: var.ahv_650_network["REC_IA_547"]  
    storage: var.ahv_650_storage["NUT_AHV_DC1_01"]  
    mem: 65535  
    cpu: 24  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.25.47.1 "  
    net_prefix: "24"  
    gw: "172.25.47.253"  
    satellite_env: DEV_TEST
  
