lan_vms:  
  LU717:  
    name: "LU717"  
    descr: "VM DE TEST"  
    hostname: "lu717"  
    datacenter: nutanix.dc1  
    image: rhel8-dc1  
    cluster: cluster650  
    subnet: var.ahv_650_network["Production"]  
    storage: var.ahv_650_storage["NUT_AHV_DC1_01"]  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "200.1.1.106"  
    net_prefix: "24"  
    gw: "200.1.1.240"  
    satellite_env: DEV_TEST
  
  LU718:  
    name: "LU718"  
    descr: "VM DE TEST"  
    hostname: "lu718"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: cluster651  
    subnet: var.ahv_651_network["Production"]  
    storage: var.ahv_651_storage["NUT_AHV_DC1_01"]  
    mem: 1500  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "200.1.1.105"  
    net_prefix: "24"  
    gw: "200.1.1.240"  
    satellite_env: DEV_TEST
  
