lan_vms:  
  VSL-TST-OES-002:  
    name: "VSL-TST-OES-002"  
    descr: "ORACLE EXACC SCRIPT LAN"  
    hostname: "vsl-test-oes-002"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: cluster651  
    subnet: var.ahv_651_network["VLAN_26"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "10"  
    ip: "192.168.26.217"  
    net_prefix: "24"  
    gw: "192.168.26.1"  
    satellite_env: DEV_TEST
  
dmz_vms:  
  VSL-TST-OES-001:  
    name: "VSL-TST-OES-001"  
    hostname: "vsl-test-oes-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-04  
    network: DMZ_EXT_Oracle_Mgmt  
    datastore: NUT_DMZ_EXT_DC2_01  
    folder: /DMZ  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "10"  
    ip: "172.22.143.100"  
    net_prefix: "24"  
    gw: "172.22.143.1"  
    vm_ip_last_octet: 100  
    gw_ip_last_octet: 1  
    subnet: 172.22.143.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
