dmz_vms:  
  VSL-PPR-RPE-001:  
    name: "VSL-PPR-RPE-001"  
    hostname: "vsl-ppr-rpe-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-02  
    network: PPR_REVERSE_PROXY_EXT  
    datastore: NUT_DMZ_EXT_DC2_01  
    folder:   
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.74.1"  
    net_prefix: "24"  
    gw: "172.24.74.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.74.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-RPI-001:  
    name: "VSL-PPR-RPI-001"  
    hostname: "vsl-ppr-rpi-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-04  
    network: PPR_REVERSE_PROXY_INT  
    datastore: NUT_DMZ_EXT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.41.1"  
    net_prefix: "24"  
    gw: "172.24.41.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.41.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-ALT-001:  
    name: "VSL-PPR-ALT-001"  
    hostname: "vsl-ppr-alt-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-06  
    network: PPR_APPLICATIONS  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.5.1"  
    net_prefix: "24"  
    gw: "172.24.5.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.5.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-APT-001:  
    name: "VSL-PPR-APT-001"  
    hostname: "vsl-ppr-apt-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-08  
    network: PPR_SERVICES  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 20480  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.0.1"  
    net_prefix: "24"  
    gw: "172.24.0.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.0.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-MST-001:  
    name: "VSL-PPR-MST-001"  
    hostname: "vsl-ppr-mst-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-02  
    network: PPR_SERVICES  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 20480  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.0.2"  
    net_prefix: "24"  
    gw: "172.24.0.254"  
    vm_ip_last_octet: 2  
    gw_ip_last_octet: 254  
    subnet: 172.24.0.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-EPT-001:  
    name: "VSL-PPR-EPT-001"  
    hostname: "vsl-ppr-ept-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-04  
    network: PPR_EPTS  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 8192  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.23.1"  
    net_prefix: "24"  
    gw: "172.24.23.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.23.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-KAF-001:  
    name: "VSL-PPR-KAF-001"  
    hostname: "vsl-ppr-kaf-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-06  
    network: PPR_TECH_COMPONENTS  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 8192  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.11.1"  
    net_prefix: "24"  
    gw: "172.24.11.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.11.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-ATQ-001:  
    name: "VSL-PPR-ATQ-001"  
    hostname: "vsl-ppr-atq-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-08  
    network: PPR_SERVICES_LN  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 16384  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.1.1"  
    net_prefix: "24"  
    gw: "172.24.1.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.1.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-ATQ-002:  
    name: "VSL-PPR-ATQ-002"  
    hostname: "vsl-ppr-atq-002"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-02  
    network: PPR_SERVICES_LN  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 8192  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.1.2"  
    net_prefix: "24"  
    gw: "172.24.1.254"  
    vm_ip_last_octet: 2  
    gw_ip_last_octet: 254  
    subnet: 172.24.1.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-MSN-001:  
    name: "VSL-PPR-MSN-001"  
    hostname: "vsl-ppr-msn-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-04  
    network: PPR_SERVICES_LN  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 8192  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.1.3"  
    net_prefix: "24"  
    gw: "172.24.1.254"  
    vm_ip_last_octet: 3  
    gw_ip_last_octet: 254  
    subnet: 172.24.1.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-ABN-001:  
    name: "VSL-PPR-ABN-001"  
    hostname: "vsl-ppr-abn-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-06  
    network: PPR_SERVICES_LN  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 16384  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.1.4"  
    net_prefix: "24"  
    gw: "172.24.1.254"  
    vm_ip_last_octet: 4  
    gw_ip_last_octet: 254  
    subnet: 172.24.1.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-ALN-001:  
    name: "VSL-PPR-ALN-001"  
    hostname: "vsl-ppr-aln-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-08  
    network: PPR_APPLICATIONS_LN  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 16384  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.6.1"  
    net_prefix: "24"  
    gw: "172.24.6.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.6.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-ABV-001:  
    name: "VSL-PPR-ABV-001"  
    hostname: "vsl-ppr-abv-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-02  
    network: PPR_SERVICES_LV  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.2.1"  
    net_prefix: "24"  
    gw: "172.24.2.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.2.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-MSV-001:  
    name: "VSL-PPR-MSV-001"  
    hostname: "vsl-ppr-msv-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-04  
    network: PPR_SERVICES_LV  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.2.2"  
    net_prefix: "24"  
    gw: "172.24.2.254"  
    vm_ip_last_octet: 2  
    gw_ip_last_octet: 254  
    subnet: 172.24.2.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-ABD-001:  
    name: "VSL-PPR-ABD-001"  
    hostname: "vsl-ppr-abd-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-06  
    network: PPR_SERVICES_DKV  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 8192  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.3.1"  
    net_prefix: "24"  
    gw: "172.24.3.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.3.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
  VSL-PPR-ABA-001:  
    name: "VSL-PPR-ABA-001"  
    hostname: "vsl-ppr-aba-001"  
    datacenter: NUT-DMZ-DC02  
    content_library_item: esx_lib2_item  
    host: nut-dmz-08  
    network: PPR_SERVICES_APROBAT  
    datastore: NUT_DMZ_INT_DC2_01  
    folder: /DMZ/Pre Prod  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "172.24.4.1"  
    net_prefix: "24"  
    gw: "172.24.4.254"  
    vm_ip_last_octet: 1  
    gw_ip_last_octet: 254  
    subnet: 172.24.4.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: DEV_TEST
  
