lan_vms:  
  VSL-DEV-APT-001:  
    name: "VSL-DEV-APT-001"  
    descr: "VSL-DEV-APT-001"  
    hostname: "vsl-dev-apt-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 20480  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.138"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-ABN-001:  
    name: "VSL-DEV-ABN-001"  
    descr: "VSL-DEV-ABN-001"  
    hostname: "vsl-dev-abn-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 16384  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.144"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-ABV-001:  
    name: "VSL-DEV-ABV-001"  
    descr: "VSL-DEV-ABV-001"  
    hostname: "vsl-dev-abv-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.150"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-ABD-001:  
    name: "VSL-DEV-ABD-001"  
    descr: "VSL-DEV-ABD-001"  
    hostname: "vsl-dev-abd-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 8192  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.151"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-ABA-001:  
    name: "VSL-DEV-ABA-001"  
    descr: "VSL-DEV-ABA-001"  
    hostname: "vsl-dev-aba-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.152"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-MST-001:  
    name: "VSL-DEV-MST-001"  
    descr: "VSL-DEV-MST-001"  
    hostname: "vsl-dev-mst-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 20480  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.161"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-MSN-001:  
    name: "VSL-DEV-MSN-001"  
    descr: "VSL-DEV-MSN-001"  
    hostname: "vsl-dev-msn-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 8192  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.188"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
  VSL-DEV-MSV-001:  
    name: "VSL-DEV-MSV-001"  
    descr: "VSL-DEV-MSV-001"  
    hostname: "vsl-dev-msv-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: pe_lu651  
    subnet: var.ahv_651_network["New_PROD 192.168.25.x"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 4096  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "50"  
    ip: "192.168.25.189"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: DEV_TEST
  
