lan_vms:  
  LU718:  
    name: "LU718"  
    descr: "VM TEST LNX"  
    hostname: "lu718"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: cluster651  
    subnet: var.ahv_651_network["Production"]  
    storage: var.ahv_651_storage["NUT_AHV_DC1_01"]  
    mem: 2048  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "200.1.1.105"  
    net_prefix: "24"  
    gw: "200.1.1.240"  
    satellite_env: DEV_TEST
  
  VSL-POC-AIA-001:  
    name: "VSL-POC-AIA-001"  
    descr: "AIA POC LNX"  
    hostname: "vsl-poc-aia-001"  
    datacenter: nutanix.dc3  
    image: rhel8-dc3  
    cluster: cluster651  
    subnet: var.ahv_651_network["New_PROD"]  
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]  
    mem: 16384  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "192.168.25.106"  
    net_prefix: "24"  
    gw: "192.168.25.1"  
    satellite_env: PROD
  
  LU717:  
    name: "LU717"  
    descr: "VM TEST LINUX -- kwk --"  
    hostname: "lu717"  
    datacenter: nutanix.dc1  
    image: rhel8-dc1  
    cluster: cluster650  
    subnet: var.ahv_650_network["Production"]  
    storage: var.ahv_650_storage["NUT_AHV_DC1_01"]  
    mem: 2048  
    cpu: 1  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "200.1.1.106"  
    net_prefix: "24"  
    gw: "200.1.1.240"  
    satellite_env: DEV_TEST
  
