lan_vms:  
dmz_vms:  
  VSL-PRO-SAT-01:  
    name: "VSL-PRO-SAT-01"  
    hostname: "vsl-pro-sat-01"  
    datacenter: NUT-DMZ-DC01  
    content_library_item: esx_lib1_item  
    host: nut-dmz-01  
    network: DMZ_MGMT_VLAN20  
    datastore: NUT_DMZ_INT_DC1_to_DC2  
    folder: /DMZ/MGMT  
    mem: 49152  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "500"  
    ip: "172.22.56.11"  
