lan_vms:
  lu717:
    name: "LU717 - LNX - VM TEST KWAKOU"
    descr: "VM DE TEST"
    hostname: "lu717"
    datacenter: nutanix.dc1
    image: rhel8-dc1
    cluster: cluster480
    subnet: var.ahv_480_network["Production"]
    storage: var.ahv_480_storage["NUT_AHV_LU480_DC01_01"]
    mem: 2048
    cpu: 1
    cpu_socket: 1
    disk2_size_gb: "100"
    ip: "200.1.1.106"
    net_prefix: "24"
    gw: "200.1.1.240"
    domain: "lalux.local"     
    dns1: "200.1.1.163"
    dns2: "200.1.1.218"
    user: "localadmin"
    pubkey: |
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUxJXxD/SFkaQ2FcFtEH3aOFlSO1De0+PEnOUj9lIIYSMY0nimo6epyEfv7NtJwQBPHWJYOzoUAe49b4rB/y8ZXR3C+xEKspD7ebqbQC9hV6gFN7My+gnTuSVsYtUXwMSuyRuKne/xu2TfTQYpImJt4UnByy5UBbs+ifQDWB+goZSMPkgP45oiTCLnioGwVQbXks5O7kI3IInvEc31iPA4RVusxmk6QEHze5J10AcCEy03RVPXuYB3KNsI2UXeevZdMV612doty1IE36qgRZW5xNYUeS25XNrOVNMyRWoQWJYLvx5rryBp69BtNg1hUjx3b+OxlNEhnfIqzSK6uXAeEij2/DHcjwOqSCjY6JmkCh7dAbWVIEq96faHF9C3IlT6gbF3RtkFaZ5hvtcWiybmJKZMeDw0YNW2/HqXRxwaW8q+Qjue/Su9AmILIUb3xzZwdUMLpG0sCV/R+NA1EVl0PMkUECRI5ZtNgfU83TmLCDOqY2MI3lw8xcjWh1eC/NU= mk417@lalux.local@rh-subman.lalux.local"
    satellite_env: "DEV_TEST"
    
  lu718:
    name: "LU718 - LNX - VM TEST KWAKOU"
    descr: "VM DE TEST"
    hostname: "lu718"
    datacenter: nutanix.dc3
    image: rhel8-dc3
    cluster: cluster651
    subnet: var.ahv_651_network["Production"]
    storage: var.ahv_651_storage["NUT_AHV_DC3_01"]
    mem: 4096
    cpu: 2
    cpu_socket: 1
    disk2_size_gb: "100"
    ip: "200.1.1.105"
    net_prefix: "24"
    gw: "200.1.1.240"
    domain: "lalux.local"     
    dns1: "200.1.1.163"
    dns2: "200.1.1.218"
    user: "localadmin"
    pubkey: |
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUxJXxD/SFkaQ2FcFtEH3aOFlSO1De0+PEnOUj9lIIYSMY0nimo6epyEfv7NtJwQBPHWJYOzoUAe49b4rB/y8ZXR3C+xEKspD7ebqbQC9hV6gFN7My+gnTuSVsYtUXwMSuyRuKne/xu2TfTQYpImJt4UnByy5UBbs+ifQDWB+goZSMPkgP45oiTCLnioGwVQbXks5O7kI3IInvEc31iPA4RVusxmk6QEHze5J10AcCEy03RVPXuYB3KNsI2UXeevZdMV612doty1IE36qgRZW5xNYUeS25XNrOVNMyRWoQWJYLvx5rryBp69BtNg1hUjx3b+OxlNEhnfIqzSK6uXAeEij2/DHcjwOqSCjY6JmkCh7dAbWVIEq96faHF9C3IlT6gbF3RtkFaZ5hvtcWiybmJKZMeDw0YNW2/HqXRxwaW8q+Qjue/Su9AmILIUb3xzZwdUMLpG0sCV/R+NA1EVl0PMkUECRI5ZtNgfU83TmLCDOqY2MI3lw8xcjWh1eC/NU= mk417@lalux.local@rh-subman.lalux.local"
    satellite_env: "DEV_TEST"


  lu625:
    name: "LU625 - LNX - VM TEST KWAKOU"
    descr: "VM DE TEST"
    hostname: "lu625"
    datacenter: nutanix.dc3
    image: rhel8-dc3
    cluster: cluster650
    subnet: var.ahv_650_network["Production"]
    storage: var.ahv_650_storage["NUT_AHV_DC3_01"]
    mem: 2048
    cpu: 1
    cpu_socket: 1
    disk2_size_gb: "100"
    ip: "200.1.1.53"
    net_prefix: "24"
    gw: "200.1.1.240"
    domain: "lalux.local"     
    dns1: "200.1.1.163"
    dns2: "200.1.1.218"
    user: "localadmin"
    pubkey: |
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUxJXxD/SFkaQ2FcFtEH3aOFlSO1De0+PEnOUj9lIIYSMY0nimo6epyEfv7NtJwQBPHWJYOzoUAe49b4rB/y8ZXR3C+xEKspD7ebqbQC9hV6gFN7My+gnTuSVsYtUXwMSuyRuKne/xu2TfTQYpImJt4UnByy5UBbs+ifQDWB+goZSMPkgP45oiTCLnioGwVQbXks5O7kI3IInvEc31iPA4RVusxmk6QEHze5J10AcCEy03RVPXuYB3KNsI2UXeevZdMV612doty1IE36qgRZW5xNYUeS25XNrOVNMyRWoQWJYLvx5rryBp69BtNg1hUjx3b+OxlNEhnfIqzSK6uXAeEij2/DHcjwOqSCjY6JmkCh7dAbWVIEq96faHF9C3IlT6gbF3RtkFaZ5hvtcWiybmJKZMeDw0YNW2/HqXRxwaW8q+Qjue/Su9AmILIUb3xzZwdUMLpG0sCV/R+NA1EVl0PMkUECRI5ZtNgfU83TmLCDOqY2MI3lw8xcjWh1eC/NU= mk417@lalux.local@rh-subman.lalux.local"
    satellite_env: "DEV_TEST"

