lan_vms:  
  LU718:  
    name: "LU718"  
    descr: "VM DE TEST - LNX"  
    hostname: "lu718"  
    datacenter: nutanix.dc1  
    image: rhel8-dc1  
    cluster: cluster650  
    subnet: var.ahv_650_network["Production"]  
    storage: var.ahv_650_storage["NUT_AHV_DC1_01"]  
    mem: 2048  
    cpu: 2  
    cpu_socket: 1  
    disk2_size_gb: "100"  
    ip: "200.1.1.105"  
    net_prefix: "24"  
    gw: "200.1.1.240"  
    satellite_env: DEV_TEST
  
dmz_vms:  
  VSL-PRO-SAT-01:  
    name: "VSL-PRO-SAT-01"  
    hostname: "vsl-pro-sat-01"  
    datacenter: NUT-DMZ-DC01  
    content_library_item: esx_lib1_item  
    host: nut-dmz-01  
    network: DMZ_MGMT_VLAN20  
    datastore: NUT_DMZ_INT_DC1_to_DC2  
    folder: /DMZ/MGMT  
    mem: 49152  
    cpu: 4  
    cpu_socket: 1  
    disk2_size_gb: "500"  
    ip: "172.22.56.11"  
    net_prefix: "24"  
    gw: "172.22.56.1"  
    vm_ip_last_octet: 11  
    gw_ip_last_octet: 1  
    subnet: 172.22.56.0/24  
    user: localadmin  
    resource_pool: esx_pool  
    satellite_env: PROD
  
