###################### SATELLITE ENROLLMENT

- hosts: all 
  gather_facts: no
  become: true
  vars_files:
  - "{{ lookup('env','HOME') }}/infrastructure-linux/vault/satellite_creds.yml"
  roles:
  - role: satellite_enroll
    release_version: "8"
    environment_name: "{{ env }}/CCOV-LALUX-APP"

  tasks:
  - name: Run OS Updates ...
    yum:
          name: '*'
          state: latest


  - name: Create LV and FS for the application
    block:
    - name: create app_vg
      lvg:
              vg: app_vg
              pvs: /dev/sdb

    - name: create app_lv
      lvol:
              vg: app_vg
              lv: opt
              size: 90%FREE

    - name: create app xfs
      filesystem:
              fstype: xfs
              dev: /dev/mapper/app_vg-opt

    - name: mount in fstab
      mount:
              path: /opt
              src: /dev/mapper/app_vg-opt
              fstype: xfs
              state: mounted

  environment:
      no_proxy: lu711.lalux.local,172.22.56.10,lu714.linux.lalux.local,192.168.42.93

################# IDM 

- hosts: all
  become: true
  vars_files:  "{{ lookup('env','HOME') }}/infrastructure-linux/ansible_vault/idm_creds.yml"
  vars:
        HOME_DIR: "{{ lookup('env','HOME') }}"
        USER: "{{ lookup('env','USER') }}"
        nd_exp_pkg: "{{ lookup('env','HOME') }}/infrastructure-linux/playbooks/node_exporter-1.3.1.linux-amd64.tar.gz"
        nd_svc_file: "{{ lookup('env','HOME') }}/infrastructure-linux/playbooks/node-exporter.service"

  gather_facts: yes

  roles:
  - role: ipaclient
    ipaadmin_principal: admin
    ipaadmin_password: "{{ idm_password }}"
    ipaclient_domain: linux.lalux.local
    ipaclient_hostname: "{{ inventory_hostname }}.lalux.local"
    ipaclient_mkhomedir: yes
    ipaservers: lu714.linux.lalux.local
    ipaclient_force: yes
    state: present

  tasks:
  - name: set bash as default shell
    lineinfile:
      line: "{{ item }}"
      path: /etc/sssd/sssd.conf
      insertbefore: 'sssd'
      state: present
    loop:
      - "default_shell = /bin/bash"
      - "override_shell = /bin/bash"
  - name: restart sssd
    service:
            name: sssd
            state: restarted

######################  DEPLOY SSH PUBKEY

  - name: authorize ssh public key
    block:
    - name: create .ssh if not existing
      file:
        state: directory
        mode: 0700
        owner: "{{ USER }}"
        group: "{{ USER }}"
        path: "{{ HOME_DIR }}/.ssh"
    - name: deploy ssh specific pub key
      authorized_key:
            user: "{{ USER }}"
            key: "{{ lookup('file','{{ HOME_DIR }}/my_key.pub') }}"

    - name: ensure correcty possitioned access rights on /home
      file:
              path: /home/lalux.local
              owner: root
              group: root
              mode: 0711


########### MONITORING: SETUP NODE_EXPORTER SERVICE

  - name: ensure gtar command exists
    yum:
        name: tar
        state: present
        disablerepo: '*'
        enablerepo: rhel-8-for-x86_64-appstream-rpms,rhel-8-for-x86_64-baseos-rpms
  - name: copy and extract node_exporter on the target
    unarchive:
      src: "{{ nd_exp_pkg }}"
      dest: /opt/
  - name: copy the binary to /usr/local/bin
    copy:
      src: /opt/node_exporter-1.3.1.linux-amd64/node_exporter
      dest: /usr/local/bin/
      remote_src: yes
      mode: 0755
  - name: create a basic service
    copy:
      src: "{{ nd_svc_file }}"
      dest: /etc/systemd/system/
    notify: load_config_change
  - name: open required ports
    firewalld:
      port: 9100/tcp
      permanent: true
      immediate: yes
      state: enabled
    ignore_errors: true                                           #par le fait que le firewall nest pas active sur tous les hosts
  handlers:
  - name: load_config_change
    systemd:
      name: node-exporter.service
      daemon-reload: yes
      state: restarted
      enabled: yes

